version: '3.4'

services:
  manglerweb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "50883:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      
  manglerapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
#      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "50881:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro
      
  manglerbot:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    #      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "57222:80"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro