version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    cap_add:
      - SYS_NICE
    environment:
      MYSQL_DATABASE: 'manglerDb'
      # So you don't have to use root, but you can if you like
      MYSQL_USER: 'user'
      # You can use whatever password you like
      MYSQL_PASSWORD: 'password'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mangler-db:/var/lib/mysql
      - ./ManglerDb/init.sql:/docker-entrypoint-initdb.d/init.sql
  
  manglerweb:
    image: ${DOCKER_REGISTRY-}manglerweb
    build:
      context: .
      dockerfile: ManglerWeb/Dockerfile
    depends_on: 
      - manglerapi

  manglerapi:
    image: ${DOCKER_REGISTRY-}manglerapi
    build:
      context: .
      dockerfile: ManglerAPI/Dockerfile
    depends_on: 
      - db
  
  
volumes:
  mangler-db:
    driver: local

