version: '3.8'

services:
  
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - '27017:27017'
    volumes:
      - manglerdb:/data/db
        
  manglerapi:
    image: ${DOCKER_REGISTRY-}manglerapi
    build:
      context: .
      dockerfile: ManglerAPI/Dockerfile
    depends_on:
      - mongodb

  manglerweb:
    image: ${DOCKER_REGISTRY-}manglerweb
    build:
      context: .
      dockerfile: ManglerWeb/Dockerfile
    depends_on: 
      - manglerapi
        
  manglerbot:
    image: ${DOCKER_REGISTRY-}manglerbot
    build:
      context: .
      dockerfile: ManglerBot/Dockerfile
    depends_on:
      - manglerapi
        
volumes:
  manglerdb:
