# This is a generated file. Not intended for manual editing.
version: "3.8"
services:
  manglerapi:
    build:
      context: "/Users/jbleu/RiderProjects/story-mangler"
      dockerfile: "ManglerAPI/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-arm64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/Users/jbleu/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/Users/jbleu/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "manglerapi:dev"
    ports:
    - "127.0.0.1:57075:57100"
    - "127.0.0.1:57275:57300"
    volumes:
    - "/Users/jbleu/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/Users/jbleu/RiderProjects/story-mangler/ManglerAPI:/app:rw"
    - "/Users/jbleu/RiderProjects/story-mangler:/src:rw"
    - "/Users/jbleu/.local/share/JetBrains/RiderRemoteDebugger/2023.2.2/LinuxArm64:/riderDebugger"
    - "/Applications/Rider.app/Contents/bin:/riderLogsConf"
    - "/Users/jbleu/Library/Logs/JetBrains/Rider2023.2/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_10_08_29_10:/riderLogs:rw"
    working_dir: "/app"
  manglerbot:
    build:
      context: "/Users/jbleu/RiderProjects/story-mangler"
      dockerfile: "ManglerBot/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-arm64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/Users/jbleu/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/Users/jbleu/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "manglerbot:dev"
    ports:
    - "127.0.0.1:57076:57100"
    - "127.0.0.1:57276:57300"
    volumes:
    - "/Users/jbleu/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/Users/jbleu/RiderProjects/story-mangler/ManglerBot:/app:rw"
    - "/Users/jbleu/RiderProjects/story-mangler:/src:rw"
    - "/Users/jbleu/.local/share/JetBrains/RiderRemoteDebugger/2023.2.2/LinuxArm64:/riderDebugger"
    - "/Applications/Rider.app/Contents/bin:/riderLogsConf"
    - "/Users/jbleu/Library/Logs/JetBrains/Rider2023.2/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_10_08_29_10:/riderLogs:rw"
    working_dir: "/app"
  manglerweb:
    build:
      context: "/Users/jbleu/RiderProjects/story-mangler"
      dockerfile: "ManglerWeb/Dockerfile"
      target: "base"
    command: []
    entrypoint:
    - "/riderDebugger/linux-arm64/dotnet/dotnet"
    - "/riderDebugger/JetBrains.Debugger.Worker.exe"
    - "--mode=server"
    - "--frontend-port=57100"
    - "--backend-port=57300"
    environment:
      ASPNETCORE_STATICWEBASSETS: "/app/bin/Debug/net7.0/ManglerWeb.staticwebassets.runtime.CT.json"
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      NUGET_PACKAGES: "/Users/jbleu/.nuget/packages"
      NUGET_FALLBACK_PACKAGES: "/Users/jbleu/.nuget/packages"
      RIDER_DEBUGGER_LOG_DIR: "/riderLogs"
      RESHARPER_LOG_CONF: "/riderLogsConf/backend-log.xml"
    image: "manglerweb:dev"
    ports:
    - "127.0.0.1:57077:57100"
    - "127.0.0.1:57277:57300"
    volumes:
    - "/Users/jbleu/.nuget/packages:/root/.nuget/fallbackpackages"
    - "/Users/jbleu/RiderProjects/story-mangler/ManglerWeb:/app:rw"
    - "/Users/jbleu/RiderProjects/story-mangler:/src:rw"
    - "/Users/jbleu/.local/share/JetBrains/RiderRemoteDebugger/2023.2.2/LinuxArm64:/riderDebugger"
    - "/Applications/Rider.app/Contents/bin:/riderLogsConf"
    - "/Users/jbleu/Library/Logs/JetBrains/Rider2023.2/DebuggerWorker/JetBrains.Debugger.Worker.2023_10_10_08_29_10:/riderLogs:rw"
    working_dir: "/app"
